#!/bin/bash
# Copyright (c) 2005, Denis Sacchet
# All rights reserved.
# $Header: $
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#     * this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#     * notice, this list of conditions and the following disclaimer in the
#     * documentation and/or other materials provided with the distribution.
#     * Neither the name of the <ORGANIZATION> nor the names of its
#     * contributors may be used to endorse or promote products derived from
#     * this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

if [ `id -u` -ne 0 ]
then
	echo "Ce script doit être lancé par le superuser"
	exit "1"
fi

if [ -r /etc/conf.d/server-tools ] 
then
	source /etc/conf.d/server-tools
else
	echo "Il faut créer le fichier /etc/conf.d/server-tools"
	exit 1
fi

if [ -z "${MAILING_LIST_REPORT}" ]
then
	echo "Il faut créer le fichier /etc/conf.d/server-tools"
	echo "et le paramétrer correctement"
	echo "Il manque le paramètre 'MAILING_LIST_REPORT'"
	exit 1
fi

source /etc/conf.d/hostname

DATE=`date +'%Y/%m/%d %H:%M'`
( /bin/echo "Serveur : ${HOSTNAME}"
/bin/echo "Date : ${DATE}"
/bin/echo "Operation : Nettoyage des fichiers inutiles"
/bin/echo "Liste des destinataires : ${MAILING_LIST_REPORT}"
SWITCH_BACK_TO_RO="no"
if [ "`mount | grep /usr | sed 's@.*(.*ro.*)@yes@'`" = "yes" ]
then
	SWITCH_BACK_TO_RO="yes"
	/bin/echo
	/bin/echo -n "Remontage de /usr en mode rw ... "
	/bin/sync
	/bin/mount -o remount,rw /usr
	if [ $? -ne 0 ]
	then
		/bin/echo "NOT OK [$?]"
		exit 2
	fi
	/bin/echo "OK"
fi
/bin/echo
/bin/echo -n "Suppression des fichiers dans /usr/portage/distfiles (`find /usr/portage/distfiles | wc -l` fichiers, `du -skh /usr/portage/distfiles`) ... "
/bin/rm -rf /usr/portage/distfiles/* &> /dev/null
if [ $? -ne 0 ]
then
	/bin/echo "NOT OK [$?]"
else
	/bin/echo "OK"
fi
if [ "${SWITCH_BACK_TO_RO}" = "yes" ]
then
	/bin/echo
	/bin/echo -n "Remontage de /usr en mode ro ... "
	/bin/mount -o remount,ro /usr
	if [ $? -ne 0 ]
	then
		/bin/echo "NOT OK [$?]"
	else
		/bin/echo "OK"
	fi
fi
/bin/echo
/bin/echo -n "Suppression des fichiers dans /tmp (`find /tmp | wc -l` fichiers, `du -skh /tmp | cut -f 1`) ... "
/bin/rm -rf /tmp/*
if [ $? -ne 0 ]
then
	/bin/echo "NOT OK [$?]"
else
	/bin/echo "OK"
fi
/bin/echo
/bin/echo -n "Suppression des fichiers dans /var/tmp (`find /var/tmp | wc -l` fichiers, `du -skh /var/tmp | cut -f 1`) ... "
/bin/rm -rf /var/tmp/*
if [ $? -ne 0 ]
then
	/bin/echo "NOT OK [$?]"
else
	/bin/echo "OK"
fi
) | /bin/mail -s "[IT] ${HOSTNAME} - ${DATE} - CLEAN" "${MAILING_LIST_REPORT}"
