#!/bin/bash
# Copyright (c) 2005, Denis Sacchet
# All rights reserved.
# $Header: $
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#     * this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#     * notice, this list of conditions and the following disclaimer in the
#     * documentation and/or other materials provided with the distribution.
#     * Neither the name of the <ORGANIZATION> nor the names of its
#     * contributors may be used to endorse or promote products derived from
#     * this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

if [ `id -u` -ne 0 ]
then
	echo "Ce script doit être lancé par le superuser"
	exit "1"
fi

if [ -r /etc/conf.d/server-tools ] 
then
	source /etc/conf.d/server-tools
else
	echo "Il faut créer le fichier /etc/conf.d/server-tools"
	exit 1
fi


if [ -z "${MAILING_LIST_REPORT}" ]
then
	echo "Il faut créer le fichier /etc/conf.d/server-tools"
	echo "et le paramétrer correctement"
	echo "Il manque le paramètre 'MAILING_LIST_REPORT'"
	exit 1
fi

if [ -x /usr/sbin/chkrootkit ]
then
	echo "Le programme chkrootkit doit être installé pour"
	echo "pouvoir utiliser ce script"
	exit 1
fi

source /etc/conf.d/hostname

DATE=`date +'%Y/%m/%d %H:%M'`
( /bin/echo "Serveur : ${HOSTNAME}"
/bin/echo "Date : ${DATE}"
/bin/echo "Operation : Analyse de la sécurité du serveur"
/bin/echo "Liste des destinataires : ${MAILING_LIST_REPORT}"
/bin/echo
/bin/echo "Exécution de chkrootkit :"
/bin/echo
/usr/sbin/chkrootkit | egrep -v "(not infected|nothing found|no suspect files| not found|nothing deleted)"
/bin/echo "Table de montage :"
/bin/echo
/bin/mount
/bin/echo
/bin/echo "Liste des fichiers permettant l'écriture à tout le monde : "
/bin/echo
/usr/bin/find / -type f \( -perm -002 \) -exec echo {} \; 2>/dev/null
/usr/bin/find / -type d \( -perm -002 \) -exec echo {}/ \; 2>/dev/null
/bin/echo
/bin/echo "Recherche des fichiers SUID :"
/bin/echo
/usr/bin/find / -type f \( -perm -004000 -o -perm -002000 \) -exec /bin/echo {} \; 2>/dev/null
/usr/bin/find / -type d \( -perm -004000 -o -perm -002000 \) -exec /bin/echo {}/ \; 2>/dev/null

) | /bin/mail -s "[IT] ${HOSTNAME} - ${DATE} - SECURITY" "${MAILING_LIST_REPORT}"